/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { FlightRm } from './models/flight-rm';
export type { ProblemDetails } from './models/problem-details';
export type { TimePlaceRm } from './models/time-place-rm';
