/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { BookDto } from './models/book-dto';
export type { FlightRm } from './models/flight-rm';
export type { NewPassengerDto } from './models/new-passenger-dto';
export type { PassengerRm } from './models/passenger-rm';
export type { ProblemDetails } from './models/problem-details';
export type { TimePlaceRm } from './models/time-place-rm';
